### ISSUE TITLE
Music slider issue not appearing

### ISSUE THREAD

**Issue by justjsoon** [WheeledParasite/Hack-N-Slash#62]
The music slider is not appearing in the Main Menu. Additionally, the changes are on the branch I made called Volumeslider.

**Comment by gururise** [comment]
Took a look at your **Volumeslider** branch, and I'm not sure what happened, but all the fonts are black, so you can't see anything. So some change to your MenuScene kind of messed things up.

I would suggest creating a new VolumeSlider2 branch and make sure you pull from the **LATEST** changes in main.  This is what I am seeing when I run the MenuScene:
![image](https://user-images.githubusercontent.com/4380009/139970913-7775b88f-6725-40d6-8640-59f2d411298d.png)

![image](https://user-images.githubusercontent.com/4380009/139970963-a8ac79dc-5b03-4091-a527-1134fd9452ad.png)

**Comment by gururise** [comment]
Related to issue #59
