### ISSUE TITLE
Upgrade Enemy AI - Finite State Machine

### ISSUE THREAD

**Issue by gururise** [WheeledParasite/Hack-N-Slash#69]
## Summary
The current enemy AI is based is brittle and hard-coded using a chain of if-statements.  It offers little flexibility and the logic is thrown all over the place.  This is not ideal and was done only to get a quick AI up and running. Enemy AI is an issue that comes up in almost every game and thus, a design pattern has been identified and codified for such a problem. A proper implementation of enemy AI would be based off the [STATE pattern](https://gameprogrammingpatterns.com/state.html). By using a FSM, we can easily add additional complexity and behaviors to the enemy AI.

### Details
Essentially, the State Pattern describes a finite state machine (FSM). **A FSM is a "machine" or class that can be in exactly one of a finite number of states at any given time.**  The FSM can change from one state to another in response to some inputs; the change from one state to another is called a transition. An example FSM for our enemy AI would be as follows:

![image](https://user-images.githubusercontent.com/4380009/140555590-c4382c1d-db7e-4079-9511-9f9bcc4e1555.png)

A [short tutorial](https://www.youtube.com/watch?v=AD4JIXQDw0s) on transitioning between states.
Another [tutorial here](https://www.youtube.com/watch?v=dYi-i83sq5g) by Blackthronprod!

### Difficulty
**This is an intermediate to difficult task**. It will involve implementing a FSM to keep track of the enemy's current state, and then integrating the enemy AI state with the enemy Animation State (which also uses a FSM).

**Comment by WheeledParasite** [comment]
Going to leave this issue open for a while.
