### ISSUE TITLE
Add Music volume control to Pause Game Menu

### ISSUE THREAD

**Issue by gururise** [WheeledParasite/Hack-N-Slash#71]
## Summary
During gameplay, when the user presses the "ESC" key, the game will pause and bring up a menu where the player can press "Space" to resume the game.  We should also provide a music volume slider, just like we do in the StartMenu scene where the user can control the in-game music volume.

### Details
This is related to issue #59 and will perform basically the same function.
- This issue will utilize the Global Configuration Class that was implemented in #55 
- Add a music slider to the pause menu
- When the Pause Menu is brought on screen, the Music Slider value should be set to the current Music Volume.  You can get the current Music Volume via: `GlobalConfiguration.Get<float>("musicVolume");`
- When the user changes the music volume via the slider, make sure to save the value to the GlobalConfiguration class: `GlobalConfiguration.Set("musicVolume", _value_);`
- Finally, we currently set the music volume when the GameScene starts through the Start() in the [AudioManger.cs](https://github.com/WheeledParasite/Hack-N-Slash/blob/main/Assets/Scripts/AudioManager.cs) file. Since the GameScene is already started, you will need to do it another way.  **You have a few options:**

1. The "**Professional**" way to do it would be to send a C# Event when the game is unPaused. You can then register this event in the AudioManager.cs file and when the event gets sent, you can update the music volume by pulling the current value from GlobalConfiguration. This is likely the preferred method.
2. The easier way to do it would be to set the music volume when the user [resumes](https://github.com/WheeledParasite/Hack-N-Slash/blob/main/Assets/Scripts/PauseMenu.cs#L9-L13) the game. This method is a little bit less clean, as you would need to grab a reference to the AudioSource component of the MusicManager game object, so that you can adjust it's volume.

### Difficulty
- Easy-Intermediate

**Comment by justjsoon** [comment]
Applied the second method recommended.
