### ISSUE TITLE
We need a NAME!

### ISSUE THREAD

**Issue by WheeledParasite** [WheeledParasite/Hack-N-Slash#73]
# We need to Name our Game
Our placeholder name is the unoriginal Hack-N-Slash, but lets come up with something better. A good name usually conveys the concept of a game, as well as setting the initial theme/feel of a game. Any suggestions, please leave as a comment on this issue!

Couple of ideas so far:

- One Arm Bandit
- Hooligan
- Biological Matters
- Arm-O-Ree

Lets get some ideas for a **Name** going!

**Comment by gururise** [comment]
This is what the AI [GPT-J-6B model](https://6b.eleuther.ai/) suggests after giving it the prompt: _"The character has one arm and is trying to fight his way through hordes of enemies as revenge for them taking his arm. The name of the game is "_

## Result
**The character has one arm and is trying to fight his way through hordes of enemies as revenge for them taking his arm. The name of the game is** called "Armageddon" and was developed by the Canadian developer, Stormfront Studios.

### Gameplay

Armageddon is a First Person Shooter that requires players to move through an urban environment trying to survive the onslaught of enemies. It features two weapon systems, the "Helix" and the "Wave" weapon.

"Helix"

This is a short-range weapon that can be fired from the hip. It fires a powerful single shot that can be charged for a longer range.

"Wave"

This weapon is fired from the hip and has a longer range than the Helix.

**Comment by WheeledParasite** [comment]
**ARMAGEDDON**

Unless anyone has a better suggestion?

**Comment by maithamharb** [comment]
I have been thinking of many names, but don't think any of them are good for the game we are making. So I think ARMAGEDDON is the best one.

**Comment by gururise** [comment]
SAMURAI SWAMP SLAYER!!!
